export const specialOfferProducts = [
  {
    id : "1",
    title: "Title of the product",
    image: "/p1.png",
    hoverImage: "/p3.png",
    price: 1499,
    oldPrice: "2499/-",
    rating: 3.5,
    reviews: "6.2k",
    discount: "20% OFF",
  },
  {
    id : "2",
    title: "Title of the product",
    image: "/p2.png",
    hoverImage: "/p3.png",
    price: 1499,
    oldPrice: "2499/-",
    rating: 3.5,
    reviews: "6.2k",
    discount: "20% OFF",
  },
  {
    id : "3",
    title: "Title of the product",
    image: "/p3.png",
    hoverImage: "/p2.png",
    price: 1499,
    oldPrice: "2499/-",
    rating: 3.5,
    reviews: "6.2k",
    discount: "20% OFF",
  },
];
